name: Release version
on:
  push:
    branches:
      - main
jobs:

  build:
    name: Create release version and commit it
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Configure committer
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Bump version
      uses: qzb/standard-version@v1